### ISSUE TITLE
i18n failed 

### ISSUE THREAD

**Issue by ChinaXing** [yesodweb/yesod#1036] opened 2015-07-20 07:40 UTC
mkMessage "App" "messages" "en"

```
   Could not deduce (RenderMessage master AppMessage)
      arising from a use of ‘getMessageRender’
    from the context (YesodAuthEmail master, YesodAuth master)
      bound by the type signature for
                 accountRegisterHandler :: (YesodAuthEmail master,
                                            YesodAuth master) =>
                                           HandlerT Auth (HandlerT master IO) Html
      at Foundation.hs:195:27-74
    In the second argument of ‘liftM’, namely ‘getMessageRender’
    In the first argument of ‘(>>=)’, namely
      ‘(liftM (toHtml GHC.Base..) getMessageRender)’
    In a stmt of a 'do' block:
      ((liftM (toHtml GHC.Base..) getMessageRender)
       >>=
         (\ urender_aq8H
            -> (asWidgetT GHC.Base.. toWidget)
                 (urender_aq8H MsgEnterUserName)))
```

**Comment by snoyberg** [comment] 2015-07-20 13:13
There's not enough context here to know what's going on. Please provide a minimal reproducing test case.

**Comment by StevenXL** [comment] 2019-05-14 12:39
Closing due to age. Can reopen if necessary.

**Closed by StevenXL** 2019-05-14 12:39 UTC
