### ISSUE TITLE
Could not convert to AppSettings: Persistent: error loadomg PostgreSQL conf: when expecting a String, encountered Number instead

### ISSUE THREAD

**Issue by rosenk** [yesodweb/yesod#1061] opened 2015-08-22 19:26 UTC
stack with lts-3.1
$ stack new myproject yesod-postgres
$ cd myproject
$ stack build
... after a long time it compiles successfully
$ PGUSER=user PGPASS=123 PGDATABASE=test stack exec myproject
myproject: Could not convert to AppSettings: Persistent: error loadomg PostgreSQL conf: when expecting a String, encountered Number instead

Changing the password to abc workarounds the problem. 

IMHO Thats a horrific newbie experience into Yesod

**Comment by gregwebs** [comment] 2015-08-23 19:05
@rosenk can you show a diff of the change that you made? @snoyberg is this template the same as what one gets from yesod init?

**Comment by MaxGabriel** [comment] 2015-08-23 22:24
I've reproduced this before; #938 reported this issue as well. IIRC the core of the issue is that you can't differentiate a number from a string once it's wrapped in `_env:ENVNAME:`. Seems worth fixing.

**Comment by gregwebs** [comment] 2015-08-24 00:45
hmm, the problem is that the conversion is ambiguous. One thing we could do is support quoting (assuming it isn't already).

The root of this problem though is really horrible error messages from aeson. I opened a PR to address that:
https://github.com/bos/aeson/pull/280

**Comment by snoyberg** [comment] 2015-08-24 04:48
I'm in favor of fixing this by having an explicit way to tag a field as a
string, regardless of what the content looks like. Note that the yaml
library itself can do that, this is something that the yesod package's
config parsing needs to handle better.

**Comment by snoyberg** [comment] 2015-08-24 08:59
I've just pushed a commit that seems to address this correctly. Consider a setting like `"_env:PGPASS:foo-yesod"`. It will parse the `foo-yesod` default value, determine that it's a `String`, and then will not parse the PGPASS environment variable at all, instead treating it as a literal string.

On the other hand, with `"_env:PGPORT:5432"`, the `5432` parses as an integer, and therefore we'll follow the standard parse rules.

I think this is the correct approach and will work for almost all cases. The only exceptions I can think of are:

* The default value does not parse as a String; that can be fixed by wrapping it with single quotes
* Someone wants to use YAML escape characters in the environment variable. I'm OK saying we don't support that

The commit is e06a8109d08f8e60c5e00b91508039262eac02f3; can someone else review before I release this to Hackage?

Thanks for the report @rosenk. I should have thought about this harder when @MaxGabriel reported it originally.

**Comment by MaxGabriel** [comment] 2015-08-24 15:45
That sounds good to me. I documented the solution of quoting numeric values here: https://github.com/yesodweb/yesod/wiki/Configuration#parsing-numeric-values-as-strings

Both @rosenk and @tankcorko had numeric passwords, so I thought this PR might also be helpful: https://github.com/yesodweb/yesod-scaffold/pull/98/files

Having trouble getting environment variables to be used at all on https://github.com/yesodweb/yesod/commit/e06a8109d08f8e60c5e00b91508039262eac02f3, but I think that's just something weird in my local environment.

**Comment by rosenk** [comment] 2015-08-24 15:48
I would be glad to test the fix but unfortunately I don't know how. 
$ git clone https://github.com/yesodweb/yesod.git
but then I don't know how to build/install it so the stack templateing/build to use the local build

**Comment by MaxGabriel** [comment] 2015-08-24 15:53
If you're using stack, you can add a package from a git repo. Mine looks like this:

```yaml
packages:
- '.'
- location:
    git: https://github.com/yesodweb/yesod
    commit: e06a8109d08f8e60c5e00b91508039262eac02f3
  subdirs: 
    - 'yesod'
```

**Comment by rosenk** [comment] 2015-08-24 16:00
@MaxGabriel from user perspective the password is always string, so the quotation of passwords that look like numbers is very unnatural.

**Comment by rosenk** [comment] 2015-08-24 16:09
@MaxGabriel I added these lines in my test application stack.yml and it builds yesod 1.4.2 .. but seems that this is not what I need to do? the testapp still reporting the number/string error

**Comment by snoyberg** [comment] 2015-08-24 20:57
What does your settings file have in it?

**Comment by rosenk** [comment] 2015-08-25 08:07
@snoyberg I had to recompile the whole test project but it works now ... even without quotes: PGPASS=123

**Comment by snoyberg** [comment] 2015-08-25 09:01
Awesome, thanks for testing. New version is on Hackage.

**Closed by snoyberg** 2015-08-25 09:01 UTC

**Comment by gregwebs** [comment] 2015-08-25 15:37
Looks like you figured out a great solution, but I don't understand why this does not create a regression when one actually wants a number since the below is still my mental model for what is going on:

```
fromJSON (String "123") :: Result Int
Error "when expecting a Int, encountered String instead"
*Settings Data.Aeson> fromJSON (String "123") :: Result String
Success "123"
```

**Comment by snoyberg** [comment] 2015-08-25 16:34
The magic is this:

> On the other hand, with `"_env:PGPORT:5432"`, the `5432` parses as an integer, and therefore we'll follow the standard parse rules.

Since the default value is an integer, the code tries to parse the environment variable as an integer as well.
