### ISSUE TITLE
Cached resources not loading on HTTPS

### ISSUE THREAD

**Issue by jtojnar** [yesodweb/yesod#1074] opened 2015-09-14 20:09 UTC
Accessing the scaffolded site (tested on simple) through HTTPS, when the resource is already in browser’s cache yesod will return 304 but the resource will continue being downloaded.

![304](https://cloud.githubusercontent.com/assets/705123/9860392/32364336-5b2c-11e5-8a9c-8bd4f939faba.png)

After some time it will fail. Chrome will display the cached resources and Firefox won’t display the resources at all.

Yesod console shows different times:

    GET /
      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
      Status: 200 OK 0.001405s
    GET /static/css/bootstrap.css
      Params: [("etag","QRP3qj9r")]
      Accept: text/css,*/*;q=0.1
      Status: 304 Not Modified 0.00007s
    GET /static/tmp/autogen-cWdljVlQ.css
      Accept: text/css,*/*;q=0.1
      Status: 304 Not Modified 0.000056s
    GET /static/tmp/autogen-SWBGXCgb.js
      Accept: */*
      Status: 304 Not Modified 0.000063s
    GET /static/fonts/glyphicons-halflings-regular.woff
      Accept: */*
      Status: 304 Not Modified 0.00007s

For comparison, here is the output of reloading with cache disabled.

![200](https://cloud.githubusercontent.com/assets/705123/9860446/847f261c-5b2c-11e5-8044-dbbf0e403184.png)

    GET /
      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
      Status: 200 OK 0.00227s
    GET /static/css/bootstrap.css
      Params: [("etag","QRP3qj9r")]
      Accept: text/css,*/*;q=0.1
      Status: 200 OK 0.000147s
    GET /static/tmp/autogen-cWdljVlQ.css
      Accept: text/css,*/*;q=0.1
      Status: 200 OK 0.00005s
    GET /static/tmp/autogen-SWBGXCgb.js
      Accept: */*
      Status: 200 OK 0.000056s
    GET /static/fonts/glyphicons-halflings-regular.woff
      Accept: */*
      Status: 200 OK 0.000053s

**Comment by snoyberg** [comment] 2015-09-16 05:57
Are you using warp-tls for TLS support, or some kind of reverse proxy?

**Comment by jtojnar** [comment] 2015-09-16 09:46
No, unless it is included in unmodified simple scaffolded site.

Actually it looks like the site doesn’t have any TLS support, it is provided by yesod devel.

**Comment by snoyberg** [comment] 2015-09-16 11:15
Did you follow the instructions from `yesod devel` about setting the APPROOT variable for accessing the https site? It should say something like:

```
If you wish to test https capabilities, you should set the following variable:
  export APPROOT=https://127.0.0.1:3443
```

**Comment by jtojnar** [comment] 2015-09-16 16:20
Yes.

**Comment by snoyberg** [comment] 2015-09-21 02:59
I've been unable to reproduce the problem, on my system Chrome loads up the SSL-secured version - including 304 responses - without issue.

**Comment by jtojnar** [comment] 2015-11-10 20:29
Today I removed the ~/.stack directory and tried it again using following procedure, the problem still occurs.

```
stack new cachebug yesod-simple && cd cachebug
stack install yesod-bin cabal-install --install-ghc
stack init
stack build
export APPROOT=https://127.0.0.1:3443
stack exec -- yesod devel
```
resolver: lts-3.13 (yesod-bin 1.4.14)

Note that you will see 304 in the status column but the throbber will continue spinning. After some time (a minute apparently) it will time out and `(failed)` will replace 304s in the column.

It looks as if the connection wasn’t properly terminated.

**Comment by gregwebs** [comment] 2015-11-11 15:56
Do you have this problem when you run your app directly rather than through yesod devel?

**Comment by jtojnar** [comment] 2015-11-11 18:07
When running the app directly HTTPS doesn’t seem to be accessible.

**Comment by gregwebs** [comment] 2015-11-11 19:16
I think you would need to change your `warpSettings` to use SSL. So at the moment this appears to be a devel only issue.

**Comment by sarthakbagaria** [comment] 2016-07-15 10:31
I am facing the exact same issue. Here are the results of my current attempts at debugging:

**When the 304 response times out:**
In devel mode, and in production mode with keter settings as follows:

```
stanzas:
  - type: webapp
    exec: <path to executable>
    args: []
    hosts:
      - <prod host>
    port: 443
    requires-secure: true
    ssl: true
```

**When the 304 response does not time out:**
When I serve the static files using the static-files stanza of keter:

```
stanzas:
  - type: webapp
    exec: <path_to_executable>
    args: []
    hosts:
      - <prod_host>
    port: 443
    requires-secure: true
    ssl: true
    env:
        <static_root_env_variable>: <static_host>

 - type: static-files
    hosts:
        - <static_host>
    root: <path_to_static_folder>
    requires-secure: true
    middleware: 
        - headers:
             Access-Control-Allow-Origin: <path_to_prod_host>
```

**Comment by sarthakbagaria** [comment] 2016-07-25 15:29
After spending a bit more time on this, it seems the error comes up whenever the response is empty.

To test this, we can create a simple handler:
```
getTestEmptyResponseR :: Handler Value
getTestEmptyResponseR = sendWaiResponse $ W.responseBuilder H.status204 [] mempty
```

and add a route:
`/test/empty TestEmptyResponseR GET `

When making requests to this path, the response times out for https connections (devel and keter) but is successful for http connections.

On inspecting chrome://net-internals/#events the last few lines are:

Successful response:
```
t=4676 [st=9]    HTTP_TRANSACTION_READ_BODY  [dt=0]
t=4676 [st=9]    HTTP_CACHE_WRITE_DATA  [dt=0]
t=4676 [st=9] -REQUEST_ALIVE
```
Failed response:
```
t= 7163 [st=   24]   +HTTP_TRANSACTION_READ_BODY  [dt=48005]
t=55167 [st=48028]      HTTP2_STREAM_ERROR
                        --> description = "ABANDONED (stream_id=17): <request_path>"
                        --> status = -100
                        --> stream_id = 17
t=55168 [st=48029]   -HTTP_TRANSACTION_READ_BODY
                      --> net_error = -100 (ERR_CONNECTION_CLOSED)
t=55168 [st=48029]    FAILED
                      --> net_error = -100 (ERR_CONNECTION_CLOSED)
t=55168 [st=48029] -REQUEST_ALIVE
                    --> net_error = -100 (ERR_CONNECTION_CLOSED)
```
which are same as what are returned for 304 responses.

**Comment by snoyberg** [comment] 2016-07-26 16:27
Does this happen for responses with different status codes and empty bodies?

**Comment by sarthakbagaria** [comment] 2016-07-26 16:43
Yes, I have tested for 200, 204 and 304 till now.

**Comment by snoyberg** [comment] 2016-07-27 05:36
I'm still having trouble reproducing this. Can you demonstrate how to trigger this with command line tools like `curl` or `wget`?

**Comment by sarthakbagaria** [comment] 2016-07-27 12:47
I tested the response on wget and I am not sure how to make sense of it (I repeated each of these several times to be sure).

Testing the 304 response:
Successful response when static files served through static-files stanza of keter.
For devel mode and behind keter web-app:
- Chrome, firefox and safari _time out_ on https (I gave the output from chrome in the previous message), http works fine.
- Wget exits on getting the 304 response _instantly_ (no download progress bar) on both http and https. I copied the request headers from the browser for the wget request headers.

Testing the 204 response with empty body:
- Chrome, firefox and safari _time out_ on https (I gave the output from chrome in the previous message), http works fine.
- Wget 1.14 on CentOS 7: gets the response header 204, keeps running for about _40 seconds_ before exiting and saving 0 bytes to the file, on both http and https. 
- Wget 1.17.1 on OS X El Capitan: saves 0 bytes and exits on getting the 204 response _instantly_ (no download progress bar) on both http and https.

Testing the 200 response with empty body:
- Chrome, firefox and safari _time out_ on https (I gave the output from chrome in the previous message), http works fine.
- Wget: saves 0 bytes and exits on getting the 200 response _within a second_ on both http and https.

Yesod is on CentOS 7 VM.

**Comment by snoyberg** [comment] 2016-07-27 14:51
Interesting. I'm trying to isolate this further. Can you try running this and connecting to https://localhost:3000?

```haskell
#!/usr/bin/env stack
{- stack --resolver lts-6.8 runghc
   --package http-reverse-proxy
   --package warp-tls
   --package async
   --package http-client-tls
 -}
{-# LANGUAGE OverloadedStrings #-}
import Network.HTTP.ReverseProxy
       (waiProxyTo, ProxyDest(..), WaiProxyResponse(..), defaultOnExc)
import Network.HTTP.Types (status200)
import Network.Wai (Application, responseBuilder)
import Network.Wai.Handler.Warp (defaultSettings, runSettings, setPort)
import Network.Wai.Handler.WarpTLS (runTLS, defaultTlsSettings)
import Control.Concurrent.Async (race_)
import Network.HTTP.Client (Manager, newManager)
import Network.HTTP.Client.TLS (tlsManagerSettings)

emptyApp :: Application
emptyApp _ send = send $ responseBuilder status200 [] mempty

reverseApp :: Manager -> Application
reverseApp man =
    waiProxyTo
        (const $ return $ WPRProxyDest $ ProxyDest "localhost" 3001)
        defaultOnExc
        man

main :: IO ()
main = do
    man <- newManager tlsManagerSettings
    race_
        (runTLS
             defaultTlsSettings
             (setPort 3000 defaultSettings)
             (reverseApp man))
        (runSettings (setPort 3001 defaultSettings) emptyApp)
```

**Comment by sarthakbagaria** [comment] 2016-07-27 14:57
Oh wait, I decided to test by building a new project again with the latest libraries, and the response seems to working fine on Chrome now. I wonder if the issue was solved in a recent update of some library. That would explain why you were not able to reproduce it. And maybe I was using a new version of keter which didn't have the problem, so the static-files stanza was working fine. I'll test thoroughly on the new setup and get back to you.

**Comment by snoyberg** [comment] 2016-07-27 14:59
Awesome, thank you :)

**Comment by sarthakbagaria** [comment] 2016-07-28 18:23
I updated Yesod and Keter and the problem is fixed now. I have tested in Chrome, Firefox and Safari, in devel mode and behind Keter.

I also tested on an old version of Keter, and it seems the problem was common to old versions of Keter and Yesod. I somehow happened to use an older Yesod with newer Keter because of which web-app stanza was giving error, but static-files stanza wasn't.

**Comment by snoyberg** [comment] 2016-07-28 19:11
Awesome, thank you for the testing on this.

**Closed by snoyberg** 2016-07-28 19:11 UTC
