### ISSUE TITLE
update ghci code and instructions for stack ghci

### ISSUE THREAD

**Issue by wolftune** [yesodweb/yesod#1077] opened 2015-09-28 02:05 UTC
For example, https://github.com/yesodweb/yesod/wiki/ghci still says to use `cabal repl`, and it would be nice if all this and the relevant code was restructured around `stack ghci`

**Comment by kjameslubin** [comment] 2015-10-12 18:11
I'd like to second this. We've started working with designers who are used to rapid reload capability. The speed of recompilation is a more important concern than a task runner or watcher doing a hot reload. The in `ghci` recompile method is useful, but I can never quite get stack ghci to work. 

We've moved over completely to stack from cabal, but stack ghci does not work as seamlessly as stack usually does, and possibly compares negatively to `cabal repl`.

**Comment by gregwebs** [comment] 2015-10-12 19:16
What's not working?

**Comment by kjameslubin** [comment] 2015-10-12 19:34
@gregwebs `stack ghci` works fine with a fresh yesod scaffold but doesn't seem to work well when other dependencies are present. I can try to get a minimal reproducible example together (and maybe this should be a `stack` issue, but I stopped in here first) but my error trace looks like:

```
/home/kjameslubin/haskell/blockapps-portal/blockapps-portal/.stack-work/downloaded/291bbfd7ccdf620dc468888debb4fd9b8e311b3466426dee0c34f3693b39220f.git/Yesod/Auth/OAuth2.hs:45:15:
    Not in scope: type constructor or class ‘Show’
...
```
The package in question is a forked copy of yesod-auth-oauth2 referenced via git commit.

**Comment by gregwebs** [comment] 2015-10-12 19:41
I have seen this issue also. Can you report it to stack?

**Comment by jezen** [comment] 2020-01-25 22:50
This is old, and also appears to be fixed. Closing.

**Closed by jezen** 2020-01-25 22:50 UTC
