### ISSUE TITLE
Yesod-bin doesn't compile with lts-5.16 on Windows

### ISSUE THREAD

**Issue by mrijkeboer** [yesodweb/yesod#1231] opened 2016-05-12 07:51 UTC
When I try to install yesod-bin on Windows 10 (x64) with lts-5.16 I get the error below. When using lts-5.15 it works without issues.

```
>stack build yesod-bin
Run from outside a project, using implicit global project config
Using resolver: lts-5.16 from implicit global project's config file: C:\Users\xxx\AppData\Roaming\stack\global-project\stack.yaml
Setting codepage to UTF-8 (65001) to ensure correct output from GHC
yesod-bin-1.4.18.1: configure
yesod-bin-1.4.18.1: build

--  While building package yesod-bin-1.4.18.1 using:
      C:\Users\xxx\AppData\Roaming\stack\setup-exe-cache\setup-Simple-Cabal-1.22.5.0-x86_64-windows-ghc-7.10.3.exe --builddir=.stack-work\dist\2672c1f3 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Users\xxx\AppData\Roaming\stack\global-project\.stack-work\logs\yesod-bin-1.4.18.1.log

    Configuring yesod-bin-1.4.18.1...
    Warning: This package indirectly depends on multiple versions of the same
    package. This is highly likely to cause a compile failure.
    package time-1.5.0.1 requires Win32-2.3.1.0
    package process-1.2.3.0 requires Win32-2.3.1.0
    package ghc-7.10.3 requires Win32-2.3.1.0
    package directory-1.2.2.0 requires Win32-2.3.1.0
    package x509-system-1.6.3 requires Win32-2.3.1.1
    package unix-compat-0.4.1.4 requires Win32-2.3.1.1
    package time-1.5.0.1 requires Win32-2.3.1.1
    package streaming-commons-0.1.15.4 requires Win32-2.3.1.1
    package process-1.2.3.0 requires Win32-2.3.1.1
    package hourglass-0.2.10 requires Win32-2.3.1.1
    package fast-logger-2.4.6 requires Win32-2.3.1.1
    package easy-file-0.2.1 requires Win32-2.3.1.1
    package directory-1.2.2.0 requires Win32-2.3.1.1
    package cryptonite-0.15 requires Win32-2.3.1.1
    package ansi-terminal-0.6.2.3 requires Win32-2.3.1.1
    package Win32-notify-0.3.0.1 requires Win32-2.3.1.1
    package process-1.2.3.0 requires directory-1.2.2.0
    package hpc-0.6.0.2 requires directory-1.2.2.0
    package ghc-7.10.3 requires directory-1.2.2.0
    package bin-package-db-0.0.0.0 requires directory-1.2.2.0
    package yesod-bin-1.4.18.1 requires directory-1.2.2.0
    package yaml-0.8.17.1 requires directory-1.2.2.0
    package x509-system-1.6.3 requires directory-1.2.2.0
    package wai-extra-3.0.15.1 requires directory-1.2.2.0
    package unix-compat-0.4.1.4 requires directory-1.2.2.0
    package tar-0.5.0.3 requires directory-1.2.2.0
    package streaming-commons-0.1.15.4 requires directory-1.2.2.0
    package shakespeare-2.0.8.2 requires directory-1.2.2.0
    package project-template-0.2.0 requires directory-1.2.2.0
    package process-1.2.3.0 requires directory-1.2.2.0
    package fsnotify-0.2.1 requires directory-1.2.2.0
    package file-embed-0.0.10 requires directory-1.2.2.0
    package fast-logger-2.4.6 requires directory-1.2.2.0
    package easy-file-0.2.1 requires directory-1.2.2.0
    package conduit-extra-1.1.13.1 requires directory-1.2.2.0
    package Win32-notify-0.3.0.1 requires directory-1.2.2.0
    package Cabal-1.22.8.0 requires directory-1.2.2.0
    package yesod-bin-1.4.18.1 requires process-1.2.3.0
    package x509-system-1.6.3 requires process-1.2.3.0
    package streaming-commons-0.1.15.4 requires process-1.2.3.0
    package shakespeare-2.0.8.2 requires process-1.2.3.0
    package optparse-applicative-0.12.1.0 requires process-1.2.3.0
    package conduit-extra-1.1.13.1 requires process-1.2.3.0
    package Cabal-1.22.8.0 requires process-1.2.3.0
    package ghc-7.10.3 requires process-1.2.3.0
    package yesod-bin-1.4.18.1 requires time-1.5.0.1
    package warp-3.2.2 requires time-1.5.0.1
    package wai-logger-2.2.7 requires time-1.5.0.1
    package wai-extra-3.0.15.1 requires time-1.5.0.1
    package unix-compat-0.4.1.4 requires time-1.5.0.1
    package tar-0.5.0.3 requires time-1.5.0.1
    package shakespeare-2.0.8.2 requires time-1.5.0.1
    package random-1.1 requires time-1.5.0.1
    package http-client-0.4.28 requires time-1.5.0.1
    package fsnotify-0.2.1 requires time-1.5.0.1
    package fast-logger-2.4.6 requires time-1.5.0.1
    package easy-file-0.2.1 requires time-1.5.0.1
    package directory-1.2.2.0 requires time-1.5.0.1
    package cookie-0.4.2 requires time-1.5.0.1
    package aeson-0.9.0.1 requires time-1.5.0.1
    package Cabal-1.22.8.0 requires time-1.5.0.1
    package hpc-0.6.0.2 requires time-1.5.0.1
    package ghc-7.10.3 requires time-1.5.0.1
    package directory-1.2.2.0 requires time-1.5.0.1
    Building yesod-bin-1.4.18.1...
    Preprocessing executable 'yesod-ghc-wrapper' for yesod-bin-1.4.18.1...
    [1 of 1] Compiling Main             ( ghcwrapper.hs, .stack-work\dist\2672c1f3\build\yesod-ghc-wrapper\yesod-ghc-wrapper-tmp\Main.o )
    Linking .stack-work\dist\2672c1f3\build\yesod-ghc-wrapper\yesod-ghc-wrapper.exe ...
    Preprocessing executable 'yesod-ld-wrapper' for yesod-bin-1.4.18.1...
    [1 of 1] Compiling Main             ( ghcwrapper.hs, .stack-work\dist\2672c1f3\build\yesod-ld-wrapper\yesod-ld-wrapper-tmp\Main.o )
    Linking .stack-work\dist\2672c1f3\build\yesod-ld-wrapper\yesod-ld-wrapper.exe ...
    Preprocessing executable 'yesod-ar-wrapper' for yesod-bin-1.4.18.1...
    [1 of 1] Compiling Main             ( ghcwrapper.hs, .stack-work\dist\2672c1f3\build\yesod-ar-wrapper\yesod-ar-wrapper-tmp\Main.o )
    Linking .stack-work\dist\2672c1f3\build\yesod-ar-wrapper\yesod-ar-wrapper.exe ...
    Preprocessing executable 'yesod' for yesod-bin-1.4.18.1...
    [1 of 9] Compiling GhcBuild         ( GhcBuild.hs, .stack-work\dist\2672c1f3\build\yesod\yesod-tmp\GhcBuild.o )
    [2 of 9] Compiling Build            ( Build.hs, .stack-work\dist\2672c1f3\build\yesod\yesod-tmp\Build.o )

    Build.hs:14:1: Warning:
        The import of ÔÇÿ<$>ÔÇÖ from module ÔÇÿControl.ApplicativeÔÇÖ is redundant

    Build.hs:31:1: Warning:
        The import of ÔÇÿData.MonoidÔÇÖ is redundant
          except perhaps to import instances from ÔÇÿData.MonoidÔÇÖ
        To import instances alone, use: import Data.Monoid()
    [3 of 9] Compiling HsFile           ( HsFile.hs, .stack-work\dist\2672c1f3\build\yesod\yesod-tmp\HsFile.o )
    [4 of 9] Compiling Paths_yesod_bin  ( .stack-work\dist\2672c1f3\build\autogen\Paths_yesod_bin.hs, .stack-work\dist\2672c1f3\build\yesod\yesod-tmp\Paths_yesod_bin.o )
    [5 of 9] Compiling Keter            ( Keter.hs, .stack-work\dist\2672c1f3\build\yesod\yesod-tmp\Keter.o )
    [6 of 9] Compiling Options          ( Options.hs, .stack-work\dist\2672c1f3\build\yesod\yesod-tmp\Options.o )
    [7 of 9] Compiling Devel            ( Devel.hs, .stack-work\dist\2672c1f3\build\yesod\yesod-tmp\Devel.o )
    GHC runtime linker: fatal error: I found a duplicate definition for symbol
       rgb
    whilst processing object file
       C:\Users\xxx\AppData\Local\Programs\stack\x86_64-windows\ghc-7.10.3\lib\Win32_ELFLzTRksT8Dql3wobiWvb\HSWin32-2.3.1.0-ELFLzTRksT8Dql3wobiWvb.o
    This could be caused by:
       * Loading two different object files which export the same symbol
       * Specifying the same object file twice on the GHCi command line
       * An incorrect `package.conf' entry, causing some object to be
         loaded twice.
    ghc.exe: panic! (the 'impossible' happened)
      (GHC version 7.10.3 for x86_64-unknown-mingw32):
        loadObj "C:\\Users\\xxx\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-7.10.3\\lib\\Win32_ELFLzTRksT8Dql3wobiWvb\\HSWin32-2.3.1.0-ELFLzTRksT8Dql3wobiWvb.o": failed

    Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```

**Comment by silky** [comment] 2016-05-12 13:10
interesting.

i can reproduce this (failing on lts-5.16, working on 5.15) on windows 7, 64 bit.

i found this - https://ghc.haskell.org/trac/ghc/ticket/11748

seems like this will only be fixed with ghc-8.

it's possible to get this compiler set up, however when doing this i just ran into general conflicts that i think just requires someone to set up a lts that works with this version of the compiler.

this is what i had in the `stack.yaml`:

````
flags: {}
extra-package-dbs: []
packages: []
extra-deps: []
resolver: lts-5.16

compiler: ghc-8.0.0.20160421
setup-info:
  ghc:
    windows64:
      8.0.0.20160421:
        url: "https://downloads.haskell.org/~ghc/8.0.1-rc4/ghc-8.0.0.20160421-windows-extra-src.tar.xz"
````

and this is the error i saw:

````
Setting codepage to UTF-8 (65001) to ensure correct output from GHC
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      tls: needed (>=1.3), couldn't resolve its dependencies
    needed for package: connection-0.2.5

--  Failure when adding dependencies:    
      connection: needed (>=0.2.2), couldn't resolve its dependencies
      tls: needed (>=1.2), couldn't resolve its dependencies
    needed for package: http-client-tls-0.2.4

--  Failure when adding dependencies:    
      http-client-tls: needed (>=0.2.4), couldn't resolve its dependencies
    needed for package: http-conduit-2.1.10.1

--  Failure when adding dependencies:    
      base: needed (>=4.8 && <5), 4.7.0.1 found (latest applicable is 4.8.2.0)
    needed for package: tls-1.3.7

--  Failure when adding dependencies:    
      tls: needed (>=1.3.2), couldn't resolve its dependencies
    needed for package: warp-tls-3.2.1

--  Failure when adding dependencies:    
      http-conduit: needed (>=2.1.4), couldn't resolve its dependencies
      warp-tls: needed (>=3.0.1), couldn't resolve its dependencies
    needed for package: yesod-bin-1.4.18.1
````

**Comment by snoyberg** [comment] 2016-05-12 15:20
Looks like we need to just hard-code the version of Win32 to the one shipped with GHC. I can make that change.

**Comment by snoyberg** [comment] 2016-05-15 06:56
Can you try with the latest lts release?

**Comment by silky** [comment] 2016-05-15 07:38
i can confirm that it builds fine with `lts-5.17`.

**Comment by snoyberg** [comment] 2016-05-15 09:08
Awesome, thanks!

**Closed by snoyberg** 2016-05-15 09:08 UTC
