### ISSUE TITLE
cabal install yesod fails to install on Windows XP

### ISSUE THREAD

**Issue by ioserver** [yesodweb/yesod#1232] opened 2016-05-12 23:13 UTC
In Haskell platform I run
Cabal install yesod
and got this error message at the end

[14 of 18] Compiling Text.CssCommon   ( Text\CssCommon.hs, dist\build\Text\CssCommon.o )
ghc.exe: unable to load package `time-1.5.0.1'
ghc.exe: C:\Program Files\Haskell Platform\7.10.3\lib\time_IYbjC7tGONY15oDy1fGJKz\HStime-1.5.0.1-IYbjC7tGONY15oDy1fGJKz.o: unknown symbol`__localtime32'
cabal: Error: some packages failed to install:
shakespeare-2.0.8.2 failed during the building phase. The exception was:
ExitFailure 1

How can I force the msvcr100 to be loaded?

**Comment by mgsloan** [comment] 2016-05-12 23:20
The recommended way to install yesod is [stack](haskellstack.org)

**Comment by ioserver** [comment] 2016-05-12 23:44
I have already tried stack and have a similar problem. I am using cabal to narrow down the problem.
I run
stack build yesod-bin cabal-install --install-ghc
and got this error message at the end

Progress: 40/98
--  While building package time-1.5.0.1 using:
      C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\stack5260\time-1.5.0.1\.stack-work\dist\95439361\setup\setup --builddir=.stack-work\dist\95439361 configure "--with-ghc=C:\\Program Files\\Haskell Platform\\7.10.3\\bin\\ghc.exe" "--with-ghc-pkg=C:\\Program Files\\H
askell Platform\\7.10.3\\bin\\ghc-pkg.exe" --user --package-db=clear --package-db=global --package-db=C:\stack_root\snapshots\d10ee4a2\pkgdb --libdir=C:\stack_root\snapshots\d10ee4a2\lib --bindir=C:\stack_root\snapshots\d10ee4a2\bin --datadir=C:\stack_root
\snapshots\d10ee4a2\share --libexecdir=C:\stack_root\snapshots\d10ee4a2\libexec --sysconfdir=C:\stack_root\snapshots\d10ee4a2\etc --docdir=C:\stack_root\snapshots\d10ee4a2\doc\time-1.5.0.1 --htmldir=C:\stack_root\snapshots\d10ee4a2\doc\time-1.5.0.1 --haddo
ckdir=C:\stack_root\snapshots\d10ee4a2\doc\time-1.5.0.1 --dependency=Win32=Win32-2.3.1.1-a07e3e4c81b11e778a535babb279a41f --dependency=base=base-4.8.2.0-4c21b6b50198e2dc7e7ec1b75f14f6b4 --dependency=deepseq=deepseq-1.4.1.1-a7baf140edbd1e87880c6a3cc4f61557
    Process exited with code: ExitFailure 1
    Logs have been written to: D:\haskell\sqlite\.stack-work\logs\time-1.5.0.1.log

    [1 of 1] Compiling Main             ( C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\stack5260\time-1.5.0.1\Setup.hs, C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\stack5260\time-1.5.0.1\.stack-work\dist\95439361\setup\Main.o )
    Linking C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\stack5260\time-1.5.0.1\.stack-work\dist\95439361\setup\setup.exe ...
    Configuring time-1.5.0.1...
    setup.exe: The package has a './configure' script. This requires a Unix
    compatibility toolchain such as MinGW+MSYS or Cygwin.

I have no problem installing and running stack build yesod-bin cabal-install --install-ghc in Windows 7.

**Comment by ioserver** [comment] 2016-05-12 23:48
I have already tried stack and have a similar problem. I am using cabal to narrow down the problem.
I run
stack build yesod-bin cabal-install --install-ghc
and got this error message at the end

Progress: 40/98
--  While building package time-1.5.0.1 using:
      C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\stack5260\time-1.5.0.1\.stack-work\dist\95439361\setup\setup --builddir=.stack-work\dist\95439361 configure "--with-ghc=C:\\Program Files\\Haskell Platform\\7.10.3\\bin\\ghc.exe" "--with-ghc-pkg=C:\\Program Files\\H
askell Platform\\7.10.3\\bin\\ghc-pkg.exe" --user --package-db=clear --package-db=global --package-db=C:\stack_root\snapshots\d10ee4a2\pkgdb --libdir=C:\stack_root\snapshots\d10ee4a2\lib --bindir=C:\stack_root\snapshots\d10ee4a2\bin --datadir=C:\stack_root
\snapshots\d10ee4a2\share --libexecdir=C:\stack_root\snapshots\d10ee4a2\libexec --sysconfdir=C:\stack_root\snapshots\d10ee4a2\etc --docdir=C:\stack_root\snapshots\d10ee4a2\doc\time-1.5.0.1 --htmldir=C:\stack_root\snapshots\d10ee4a2\doc\time-1.5.0.1 --haddo
ckdir=C:\stack_root\snapshots\d10ee4a2\doc\time-1.5.0.1 --dependency=Win32=Win32-2.3.1.1-a07e3e4c81b11e778a535babb279a41f --dependency=base=base-4.8.2.0-4c21b6b50198e2dc7e7ec1b75f14f6b4 --dependency=deepseq=deepseq-1.4.1.1-a7baf140edbd1e87880c6a3cc4f61557
    Process exited with code: ExitFailure 1
    Logs have been written to: D:\haskell\sqlite\.stack-work\logs\time-1.5.0.1.log

    [1 of 1] Compiling Main             ( C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\stack5260\time-1.5.0.1\Setup.hs, C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\stack5260\time-1.5.0.1\.stack-work\dist\95439361\setup\Main.o )
    Linking C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\stack5260\time-1.5.0.1\.stack-work\dist\95439361\setup\setup.exe ...
    Configuring time-1.5.0.1...
    setup.exe: The package has a './configure' script. This requires a Unix
    compatibility toolchain such as MinGW+MSYS or Cygwin.

I have no problem installing and running stack build yesod-bin cabal-install --install-ghc in Windows 7.

**Comment by mgsloan** [comment] 2016-05-12 23:58
The issue is likely related to using the haskell platform, which is an inferior way to install haskell.  Either uninstall that, or set `system-ghc: false` in your `$STACK_ROOT/config.yaml` file.  Then, use `stack setup` to install ghc.

**Comment by ioserver** [comment] 2016-05-13 02:12
I have uninstalled haskell platform. I still get the same error about package 'time-1.5.0.1'. I think the problem something to do is with running in Windows XP (32 bit). I don't know how to solve it.

D:\haskell\sqlite>stack setup
stack will use a locally installed GHC
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec

D:\haskell\sqlite>stack path
stack-root: C:\stack_root
project-root: D:\haskell\sqlite
config-location: D:\haskell\sqlite\stack.yaml
bin-path: C:\stack_root\snapshots\d10ee4a2\bin;C:\stack_root\Programs\stack\i386-windows\ghc-7.10.3\bin;C:\stack_root\Programs\stack\i386-windows\ghc-7.10.3\mingw\bin;C:\stack_root\Programs\stack\i386-windows\msys2-20150512\mingw32\bin;C:\stack_root\Progra
ms\stack\i386-windows\msys2-20150512\usr\bin;C:\stack_root\Programs\stack\i386-windows\msys2-20150512\usr\local\bin;C:\Program Files\PostgreSQL\9.5\bin;C:\Stack;Z:\MCU\ARM\OpenPilot-discovery\tools\arm-2011.03\bin;D:\bin;d:\brief;D:\Perl\site\bin;D:\Perl\b
in;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;D:\Program Files\Microsoft SDK\Bin\.;D:\Program Files\Microsoft SDK\Bin\WinNT\.;C:\Program Files\Git\cmd;C:\Program Files\CMake 2.8\bin;C:\Program Files\QuickTime\QTSystem\;C:\Program Files\Skype\P
hone\;C:\Program Files\GNU Tools ARM Embedded\4.7 2012q4\bin;C:\Program Files\GNU Tools ARM Embedded\4.6 2012q2\bin
programs: C:\stack_root\Programs\stack\i386-windows
compiler: C:\stack_root\Programs\stack\i386-windows\ghc-7.10.3\bin\ghc.exe
compiler-bin: C:\stack_root\Programs\stack\i386-windows\ghc-7.10.3\bin
local-bin: C:\Documents and Settings\Administrator\Application Data\local\bin
extra-include-dirs: C:\stack_root\Programs\stack\i386-windows\msys2-20150512\mingw32\include
extra-library-dirs: C:\stack_root\Programs\stack\i386-windows\msys2-20150512\mingw32\lib
snapshot-pkg-db: C:\stack_root\snapshots\d10ee4a2\pkgdb
local-pkg-db: D:\haskell\sqlite\.stack-work\install\e7773681\pkgdb
global-pkg-db: C:\stack_root\Programs\stack\i386-windows\ghc-7.10.3\lib\package.conf.d
ghc-package-path: D:\haskell\sqlite\.stack-work\install\e7773681\pkgdb;C:\stack_root\snapshots\d10ee4a2\pkgdb;C:\stack_root\Programs\stack\i386-windows\ghc-7.10.3\lib\package.conf.d
snapshot-install-root: C:\stack_root\snapshots\d10ee4a2
local-install-root: D:\haskell\sqlite\.stack-work\install\e7773681
snapshot-doc-root: C:\stack_root\snapshots\d10ee4a2\doc
local-doc-root: D:\haskell\sqlite\.stack-work\install\e7773681\doc
dist-dir: .stack-work\dist\95439361
local-hpc-root: D:\haskell\sqlite\.stack-work\install\e7773681\hpc
local-bin-path: C:\Documents and Settings\Administrator\Application Data\local\bin
ghc-paths: C:\stack_root\Programs\stack\i386-windows


D:\haskell\sqlite>stack build yesod-bin cabal-install --install-ghc
.....

Progress: 35/71
--  While building package optparse-applicative-0.12.1.0 using:
      C:\stack_root\setup-exe-cache\i386-windows\setup-Simple-Cabal-1.22.5.0-ghc-7.10.3.exe --builddir=.stack-work\dist\95439361 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: D:\haskell\sqlite\.stack-work\logs\optparse-applicative-0.12.1.0.log

....   

    C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\stack4700\optparse-applicative-0.12.1.0\Options\Applicative\Builder.hs:99:1: Warning:
        The import of `Monoid' from module `Data.Monoid' is redundant
    [10 of 15] Compiling Options.Applicative.BashCompletion ( Options\Applicative\BashCompletion.hs, .stack-work\dist\95439361\build\Options\Applicative\BashCompletion.o )

    C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\stack4700\optparse-applicative-0.12.1.0\Options\Applicative\BashCompletion.hs:10:1: Warning:
        The import of `<*>, <$>'
        from module `Control.Applicative' is redundant
    [11 of 15] Compiling Options.Applicative.Help.Core ( Options\Applicative\Help\Core.hs, .stack-work\dist\95439361\build\Options\Applicative\Help\Core.o )
    ghc.exe: unable to load package `time-1.5.0.1'
    ghc.exe: C:\stack_root\snapshots\d10ee4a2\lib\i386-windows-ghc-7.10.3\time-1.5.0.1-3EYeZQ8SWrsIZ2jLsmmG8m\HStime-1.5.0.1-3EYeZQ8SWrsIZ2jLsmmG8m.o: unknown symbol `__localtime32'

D:\haskell\sqlite>

**Comment by jezen** [comment] 2020-01-26 09:09
This is old, and Windows XP is no longer supported by Microsoft. I’ll close this issue.

**Closed by jezen** 2020-01-26 09:09 UTC
