### ISSUE TITLE
Yesod devel not rebuilding application properly

### ISSUE THREAD

**Issue by jaspertron** [yesodweb/yesod#972] opened 2015-04-18 22:42 UTC
I recently ran into a problem where anytime I edit ~~a file~~ config/routes, `yesod devel` says it's rebuilding the application, but the application's behavior doesn't change. For example, if I

  1. create a new project with the scaffolding
  2. run `yesod devel`
  3. edit config/routes, changing the path of HomeR from `/` to `/home`

I get:
```
Forcing recompile for ./Foundation.hs because of config/routes
Forcing recompile for ./Foundation.hs because of templates/default-layout-wrapper.hamlet
Forcing recompile for ./Foundation.hs because of templates/default-layout.hamlet
Stopping development server...
Exit code: ExitSuccess
Forcing recompile for ./Foundation.hs because of config/routes
Forcing recompile for ./Foundation.hs because of templates/default-layout-wrapper.hamlet
Forcing recompile for ./Foundation.hs because of templates/default-layout.hamlet
Forcing recompile for ./Foundation.hs because of config/routes
Forcing recompile for ./Foundation.hs because of templates/default-layout-wrapper.hamlet
Forcing recompile for ./Foundation.hs because of templates/default-layout.hamlet
Rebuilding application... (using cabal)
Starting development server...
Starting devel application
Devel application launched: http://localhost:3000
```

however, HomeR is still available at `/` and I get a 404 for `/home`.

~~I am suspicious of the `Exit code: ExitSuccess` in the above output. I don't remember seeing that when things were working properly.~~

I'm using yesod-bin version 1.4.7.1 and cabal version 1.22.2.0.

**Comment by snoyberg** [comment] 2015-04-19 05:43
Sometimes this happens with changes to the routes file, I believe it's an
issue with GHC, but I've never isolated it. To changes to other parts of
the code base get reflected?

**Comment by jaspertron** [comment] 2015-04-19 06:16
Yes, changes to Home.hs and homepage.hamlet work properly. I guess it's just the routes file.

It's happening consistently to me. Any suggestions on how I can debug this?

**Comment by snoyberg** [comment] 2015-04-19 06:24
My guess is that `Application.hs` isn't being recompiled even though an identifier it depends on `resourcesApp` is being modified. Debugging would probably be best done by reproducing this with a minimal test case, though I don't have a clear plan on how to do so.

**Comment by BlakeRain** [comment] 2015-04-19 07:08
I feel it might be worth mentioning that I have a similar issue with `yesod devel` in that changes to a route file are not detected. I don't use the scaffold, and usually have my dispatch in a separate module from my foundation type and `Yesod` instance. Changes to a routes file has always required touching the dependent module: the one using `parseRoutesFile`.

Interestingly, the same is not the case for any use `persistFileWith`; even with multiple files in different modules (various models, views and such forth) the change is detected and recompilation commences.

From what I can remember, both `persistFileWith` and `parseRoutesFileWith` use `qAddDependentFile`, so it's not clear to me why there should be a difference.

**Comment by snoyberg** [comment] 2015-04-19 07:29
I think the difference- and I haven't explored this- is that Application.hs
doesn't use qAddDependentFile on config/routes, since it doesn't depend on
it directly. Instead, it imports appResources from Foundation, which
depends on config/routes. I believe that when Foundation.hs is recompiled,
it doesn't trigger a recompile in Application.hs.

**Comment by BlakeRain** [comment] 2015-04-19 07:31
That's interesting, because I'm not seeing the recompilation of `Foundation.hs` or `Application.hs` when the routes are changed.

**Comment by snoyberg** [comment] 2015-04-19 07:32
That *is* interesting, maybe the problem is more basic than I envisioned.
@jaspertron, does that give you enough information to take a stab at
debugging this a bit farther?

**Comment by BlakeRain** [comment] 2015-04-19 07:43
I apologize if this is a stupid question, but I was looking at #955 and this got me thinking: why don't we parse the extra file dependencies (those added via `qAddDependentFile`) from the `.hi` file?

**Comment by snoyberg** [comment] 2015-04-19 07:45
Hmm.... that sounds quite interesting actually. I have no experience parsing `.hi` files, but that would be an intriguing route to follow up on.

**Comment by jaspertron** [comment] 2015-04-19 18:45
For me, changing routes causes Foundation.hs, but not Application.hs, to get recompiled.
Indeed, if I add `qAddDependentFile "config/routes"` to Application.hs (or touch it after every edit to the routes file), everything works as expected.

I can't see where Application.hs is importing appResources. Does it do that with TH? I searched this repository for "appResources" but couldn't find anything (except this issue).

**Comment by jaspertron** [comment] 2015-04-20 01:26
I see now that Application.hs imports ~~appResources~~ resourcesApp indirectly through Import.hs. I'm guessing resourcesApp gets defined by mkYesodData in Foundation.hs?

It looks like this bug was introduced in yesod-bin version 1.4.7. I tested 1.4.6 and it works as expected.

**Comment by snoyberg** [comment] 2015-04-20 04:46
Perhaps it's sufficient as a workaround to add a `qAddDependentFile "config/routes"` to Application.hs.

**Comment by snoyberg** [comment] 2015-07-19 22:51
Assuming that the `addDependentFile "config/routes"` workaround worked, closing.

**Closed by snoyberg** 2015-07-19 22:51 UTC

**Comment by lukaszsamson** [comment] 2017-07-12 10:04
The bug is still there. In freshly scaffolded project when I edit `config/routes` I can see `Foundation.hs` being recompiled but the changes to routing are not applied. Even restarting the devel process does not help.

**Comment by psibi** [comment] 2017-07-12 10:50
@lukaszsamson Can you create a new issue with relevant details including the version of yesod devel you are using ? yesod devel has been rewritten recently so I thinking opening a new issue will be more relevant.
