### ISSUE TITLE
Yesod Test Post and Session

### ISSUE THREAD

**Issue by Bernardoow** [yesodweb/yesod#1615] opened 2019-08-10 22:39 UTC
I trying to test with session when I sent twice post happend what I expected -> statusIs 200 and then statusIs 400 . When I used post and postBody .. something is broken and happend twice statusIs 200 .

Updated explanation ->
I have a aplication that works with session and has two endpoints:

1. Endpoint 1 -> Check if have data in the session. If has response with a error 400 else add data in the session.
2. Endpoint 2 -> Check if have data in the session. If has do it work with response 200 else response with a error 400

So, to tests I'm doing:

1. Example
    * post StartTheGameR
    * statusIs 201
    * post StartTheGameR
    * statusIs 400
    * **Test OK**
2. Example
     * post CreateDinosaurR
     * statusIs 400
   * **Test OK **
3. Example
    * post StartTheGameR
    * statusIs 201
     * postBody CreateDinosaurR (WithSomeBodyHere)
     * statusIs 201
    * **Test Fail -> because he say not data session. WHY? I started with the first request. Maybe because it is json at the body?**
4.Example
  *post StartTheGameR
  *statusIs 201

   * request $ do
     * setRequestBody  (WithSomeBodyHere)
     * setMethod "POST"
     * setUrl CreateDinosaurR
     * addRequestHeader (hContentType, "application/json")
     * statusIs 201
   * **Test OK**

**Comment by snoyberg** [comment] 2019-08-13 07:23
It would be much easier to follow this and help debug it with a minimal reproducing test case.

**Comment by snoyberg** [comment] 2019-08-13 11:50
In `case maybePosition`, you're ignoring the error value returned. If you print it out, you can see that you'll get a message along the lines of:

```
Error "Non-JSON content type: Nothing"
```

This is because you're using `parseCheckJsonBody`, but are not setting a `content-type`.

**Comment by Bernardoow** [comment] 2019-08-13 12:05
uhm... How I do this? Adding addRequestHeader (hContentType, "application/json") after postBody ?

I thought postBody automatically will be content-type : content-type.

Sorry for wating your time =/.

**Comment by snoyberg** [comment] 2019-08-13 12:09
I think you'd add it before. But you can test it out and find out.

**Comment by jezen** [comment] 2020-01-26 07:45
I think there is no issue here, so I'll close this.

**Closed by jezen** 2020-01-26 07:45 UTC
