### ISSUE TITLE
Constant "login invalid" error for Yesod.Auth.GoogleEmail2

### ISSUE THREAD

**Issue by codygman** [yesodweb/yesod#1133] opened 2015-12-29 05:53 UTC
I created a yesod project([minmal bug reproduction source](https://github.com/codygman/yesod-google-oauth-bug-repro)) with:

```shell
bug-repros λ stack new oauth-google-bug yesod-sqlite
Downloading template "yesod-sqlite" to create project "oauth-google-bug" in oauth-google-bug/ ...
Writing default config file to: /home/cody/programming/haskell/bug-repros/oauth-google-bug/stack.yaml
Basing on cabal files:
- /home/cody/programming/haskell/bug-repros/oauth-google-bug/oauth-google-bug.cabal

Checking against build plan lts-3.19

* Build plan did not match your requirements:
    yesod-test version 1.4.4 found
    - oauth-google-bug requires >=1.5.0.1 && <1.6


Checking against build plan lts-3.18

* Build plan did not match your requirements:
    yesod-test version 1.4.4 found
    - oauth-google-bug requires >=1.5.0.1 && <1.6


Checking against build plan nightly-2015-12-28
Selected resolver: nightly-2015-12-28
Wrote project config to: /home/cody/programming/haskell/bug-repros/oauth-google-bug/stack.yaml
```

I set my client id and secret, then tried logging in with multiple unique gmail accounts. I get redirected back to /auth/login every time and get the error message "invalid login".

Here is a log of what it looks like:

```shell
GET /
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  Status: 200 OK 0.003252s
GET /static/css/bootstrap.css
  Params: [("etag","QRP3qj9r")]
  Accept: text/css,*/*;q=0.1
  Status: 304 Not Modified 0.000141s
GET /static/tmp/autogen-hxYJ7yvP.css
  Accept: text/css,*/*;q=0.1
  Status: 304 Not Modified 0.000087s
GET /static/tmp/autogen-dvDTvJPR.js
  Accept: */*
  Status: 304 Not Modified 0.00008s
GET /auth/login
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  Status: 200 OK 0.00122s
GET /auth/page/googleemail2/forward
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  Status: 303 See Other 0.001015s
28/Dec/2015:23:36:12 -0600 [Debug#SQL] SELECT "id","ident","password" FROM "user" WHERE "ident"=?; [PersistText "myemail@gmail.com"]
GET /auth/page/googleemail2/complete
  Params: [("state","REDACTED"),("code","REDACTED")]
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  Status: 303 See Other 0.7806s
GET /auth/login
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
  Status: 200 OK 0.000657s
```
I then checked the sqlite database and found nothing had been written to it:

```shell
oauth-google-bug:master*? λ sqlite3 oauth-google-bug.sqlite3 
SQLite version 3.8.11.1 2015-07-29 20:00:57
Enter ".help" for usage hints.
sqlite> .tables
comment  email    user   
sqlite> select * from comment;
sqlite> select * from email;
sqlite> select * from user;
sqlite> 
```

I'm guessing that since all of my oauth related things seem to be working, there is an error of some sort with writing user information to the database that is failing silently somewhere? My relatively inexperienced (with Yesod) assumption being that the oauth plugins receive the access key and other information and persist it in the database.

I don't have time to debug this now, but will in the future. Any help or advice is appreciated.

**Comment by silky** [comment] 2015-12-29 06:29
the default project doesn't create new users for you.

consider this line - https://github.com/codygman/yesod-google-oauth-bug-repro/blob/master/Foundation.hs#L142

when an authentication request comes in, all your `authenticate` function does is try and look the user up. if it doesn't find it, it returns `invalid login`.

you might like to change the code to insert a new user

````
    authenticate creds = runDB $ do
        x <- getBy $ UniqueUser $ credsIdent creds
        return $ case x of
            Just (Entity uid _) -> Authenticated uid
            Nothing -> fmap Authenticated $ insert User {
                         userIdent = credsIdent creds
                       , userPassword  = Nothing
                       }
````

(for example)

**Comment by codygman** [comment] 2015-12-29 06:41
I see, perhaps a note about that would be useful in [the docs](https://github.com/yesodweb/yesod/blob/master/yesod-auth/Yesod/Auth/GoogleEmail2.hs#L22).

Thanks for your help @silky

**Comment by snoyberg** [comment] 2015-12-29 06:53
This looks like a regression introduced in https://github.com/yesodweb/yesod-scaffold/commit/20cb2bc44eb3e0bf9662b75193f184c5f3d7f212, which should be fixed. @pseudonom @gregwebs either of you have any input on this?

**Comment by codygman** [comment] 2015-12-29 07:04
That fix ended up working with a slight adjustment to the code you gave me @silky (though one that was a bit confusing imo)

Details here: https://github.com/codygman/yesod-google-oauth-bug-repro/commit/f2a9ca5d6004fefcfe889f77d5357e2d0d2b859f

**Comment by snoyberg** [comment] 2015-12-29 10:20
I've opened up a pull request for this change to the scaffolding: https://github.com/yesodweb/yesod-scaffold/pull/121

**Comment by gregwebs** [comment] 2015-12-29 15:47
Is it a regression or a change of the default? One seems better for email and the other for oauth

**Comment by snoyberg** [comment] 2015-12-29 16:01
The current behavior won't allow anyone to ever log in to the system, so I
think it's a regression for both cases. But I'm not sure if there's a
subtle point I'm missing.

**Comment by gregwebs** [comment] 2015-12-29 17:07
Okay. This looks like a copy and paste error.

**Comment by snoyberg** [comment] 2015-12-30 06:56
New version of the scaffolding is now in the stack-templates repo.

**Closed by snoyberg** 2015-12-30 06:56 UTC
